### ISSUE TITLE
error in update_contacts.ipynb

### ISSUE THREAD

**Issue by MarcusAkoev** [snorkysnark/moveon-py#1]
# Все поля contact
response = await client.queue_and_get(list_contacts_template())
response["data"]["availableKeys"].split(";")

---------------------------------------------------------------------------
StatusError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_19024/2405909387.py in <module>
      1 # Все поля contact
----> 2 response = await client.queue_and_get(list_contacts_template())
      3 response["data"]["availableKeys"].split(";")

~\Downloads\moveon-py-main\moveon-py-main\moveon.py in queue_and_get(self, data, retry_time)
     99     ) -> dict:
    100         """Queue the request, wait until it is completed, return the response body"""
--> 101         request_id = await self.queue(data)
    102         return await self.get(request_id, retry_time)
    103 

~\Downloads\moveon-py-main\moveon-py-main\moveon.py in queue(self, data)
     56 
     57         if status != "success":
---> 58             raise StatusError(status)
     59 
     60         response_data = xml["rest"]["queue"]["response"]

StatusError: Unexpected status: None

**Comment by snorkysnark** [comment]
Скорее всего, неправильно сгенерирован ssl-сертификат/хеш.
Сделал более полное сообщение об ошибке:
```
Unexpected status: None
{'rest': {'@version': '1.0', 'queue': {'response': 'Auth Failed', 'debugInfo': None, 'status': None}}}
```

**Comment by snorkysnark** [comment]
В папке cert есть пример, как его получать. Или если у тебя нету bash, см. [ноутбук](https://github.com/snorkysnark/moveon-py/blob/main/gencert.ipynb)
